#provisionung des serveurs

- hosts : devops-all
  remote_user: root
  roles :
    - common
    - docker

- hosts : swarm-manager
  remote_user: root
  tasks:
  - name: hostname
    hostname:
      name: swarm-manager
    when : ansible_distribution == 'Debian'

- hosts : swarm-worker-1
  remote_user: root
  tasks:
  - name: hostname
    hostname:
      name: swarm-worker-1
    when : ansible_distribution == 'Debian'


- hosts : swarm-worker-2
  remote_user: root
  tasks:
  - name: hostname
    hostname:
      name: swarm-worker-2
    when : ansible_distribution == 'Debian'
