#provisionung des serveurs

- hosts : devops-all
  remote_user: root
  roles :
    - common
    - docker

- hosts : swarm-manager
  remote_user: root
  tasks:
  - name: hostname
    hostname:
      name: swarm-manager
    when : ansible_distribution == 'Debian'


- hosts : swarm-worker-1
  remote_user: root
  tasks:
  - name: hostname
    hostname:
      name: swarm-worker-1
    when : ansible_distribution == 'Debian'


- hosts : swarm-worker-2
  remote_user: root
  tasks:
  - name: hostname
    hostname:
      name: swarm-worker-2
    when : ansible_distribution == 'Debian'



- name: setup pre-requisites
  hosts: all
  roles:
    - create-sudo-user


- name: initialize docker swarm
  hosts: swarm-managers
  roles:
    - docker-swarm-init

- name: add workers to the swarm
  hosts: swarm-workers
  roles:
    - docker-swarm-add-worker
